const activeState={archetypes:[],query:"",selected:null};
const activeElements={search:document.querySelector("#active-search"),updated:document.querySelector("#active-updated"),total:document.querySelector("#active-total"),grid:document.querySelector("#active-grid"),error:document.querySelector("#active-error"),dialog:document.querySelector("#active-dialog"),dialogContent:document.querySelector("#active-dialog-content")};
const escapeHtml=(value="")=>String(value).replace(/[&<>'"]/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[character]);
const dateLabel=value=>{const normalized=/^\d{4}-\d{2}-\d{2}$/.test(value)?`${value}T00:00:00`:value;const date=new Date(normalized);return Number.isNaN(date.valueOf())?"Date unavailable":new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(date);};
const cardTypeLine=card=>[card.attribute,card.cardType,card.monsterType,card.abilities?.join(" · ")].filter(Boolean).join(" · ")||card.cardType||"Card details unavailable";
const cardStats=card=>[card.levelRankLink,card.atk!==undefined?`ATK ${card.atk}`:"",card.def!==undefined?`DEF ${card.def}`:""].filter(Boolean).join(" · ");

function activeCard(entry){
  const progress=Math.min(100,entry.retirementsSeen/entry.retirementThreshold*100);
  return `<button id="archetype-${entry.id}" class="active-entry${entry.featuredImageUrl?" active-entry--featured":""}${entry.retirementRequired?" is-required":""}" type="button" data-archetype-id="${entry.id}"><span class="active-entry__details"><span class="archive-entry__tags"><span class="archive-tag">${entry.status==="revived"?"Revived":"Active"}</span>${entry.retirementRequired?'<span class="archive-tag active-tag--required">Retirement required</span>':""}</span><h2>${escapeHtml(entry.name)}</h2><p>Created by ${escapeHtml(entry.creator)}</p><div class="active-entry__facts"><span><b>${entry.registeredCardCount}</b> registered cards</span><span><b>${entry.totalClauses}</b> total clauses</span></div><div class="active-retirement"><span><b>Duelhalla progress</b><strong>${entry.retirementsSeen} / ${entry.retirementThreshold}</strong></span><i><u style="width:${progress}%"></u></i></div></span>${entry.featuredImageUrl?`<span class="active-entry__art"><img src="${escapeHtml(entry.featuredImageUrl)}" alt="Featured artwork from ${escapeHtml(entry.featuredCardName||entry.name)}" loading="lazy" /></span>`:""}</button>`;
}
function renderActive(){
  const query=activeState.query.trim().toLowerCase();const entries=activeState.archetypes.filter(entry=>!query||`${entry.name} ${entry.creator}`.toLowerCase().includes(query));
  activeElements.grid.innerHTML=entries.length?entries.map(activeCard).join(""):`<p class="league-empty">${activeState.archetypes.length?"No active archetypes match that search.":"Active archetypes will appear after the updated bot publishes league data."}</p>`;
}
function archetypeDialog(entry){
  return `<div class="archive-dialog__body" style="--archive-color:#e2b84a"><div class="archive-dialog__topline"><span class="archive-tag">${entry.status==="revived"?"Revived":"Active"}</span>${entry.retirementRequired?'<span class="archive-tag active-tag--required">Retirement required</span>':""}${entry.registeredCardCount<entry.declaredCardCount?'<span class="archive-tag archive-tag--incomplete">Registration incomplete</span>':""}</div><h2>${escapeHtml(entry.name)}</h2><p class="archive-dialog__creator">Created by ${escapeHtml(entry.creator)} · Active since ${dateLabel(entry.activatedAt)}</p><div class="archive-facts"><div><span>Registered cards</span><strong>${entry.registeredCardCount} / ${entry.declaredCardCount}</strong></div><div><span>Effect clauses</span><strong>${entry.totalClauses} (${entry.baseClauses} base + ${entry.addedClauses} added)</strong></div><div><span>Duelhalla progress</span><strong>${entry.retirementsSeen} / ${entry.retirementThreshold}</strong></div></div>${entry.description?`<p class="archive-note">${escapeHtml(entry.description)}</p>`:""}<div class="archive-cards-heading"><h3>Registered cards</h3><span>${entry.cards.length} linked</span></div><div class="archive-card-grid">${entry.cards.length?entry.cards.map(card=>`<button class="archive-card" type="button" data-card-id="${card.id}">${card.imageUrl?`<img src="${escapeHtml(card.imageUrl)}" alt="${escapeHtml(card.name)} artwork" loading="lazy" />`:'<span class="archive-card__placeholder">YF</span>'}<div><strong>${escapeHtml(card.name)}</strong><span>${escapeHtml(card.cardType||"Card details")}</span></div></button>`).join(""):'<p class="archive-empty">No cards have been registered with the bot yet.</p>'}</div></div>`;
}
function cardDialog(card){
  const details=[["Card type",card.cardType],["Monster type",card.monsterType],["Attribute",card.attribute],["Level / Rank / Link",card.levelRankLink],["ATK",card.atk],["DEF",card.def],["Ability",card.abilities?.join(", ")],["Spell / Trap type",card.spellTrapType],["Pendulum scale",card.pendulumScale],["Link markers",card.linkMarkers?.join(", ")]].filter(([,value])=>value!==undefined&&value!==null&&value!=="");
  return `<div class="archive-card-detail"><div>${card.imageUrl?`<img class="archive-card-detail__art" src="${escapeHtml(card.imageUrl)}" alt="${escapeHtml(card.name)} artwork" />`:'<div class="archive-card__placeholder">YF</div>'}</div><div><button class="archive-back" type="button">← Back to archetype</button><h2>${escapeHtml(card.name)}</h2><p class="archive-card-detail__line">${escapeHtml(cardTypeLine(card))}</p>${cardStats(card)?`<p class="archive-card-detail__line">${escapeHtml(cardStats(card))}</p>`:""}${details.length?`<dl class="detail-grid">${details.map(([label,value])=>`<div class="detail-item"><dt>${escapeHtml(label)}</dt><dd>${escapeHtml(value)}</dd></div>`).join("")}</dl>`:""}${card.pendulumEffect?`<div class="archive-card-detail__text"><strong>Pendulum effect</strong><br>${escapeHtml(card.pendulumEffect)}</div>`:""}<div class="archive-card-detail__text">${escapeHtml(card.text||"No card text is currently available.")}</div></div></div>`;
}
function openArchetype(id){const entry=activeState.archetypes.find(item=>item.id===id);if(!entry)return;activeState.selected=entry;activeElements.dialogContent.innerHTML=archetypeDialog(entry);activeElements.dialog.showModal();}
document.addEventListener("click",event=>{const entry=event.target.closest("[data-archetype-id]");if(entry)openArchetype(Number(entry.dataset.archetypeId));const card=event.target.closest("[data-card-id]");if(card&&activeState.selected){const found=activeState.selected.cards.find(item=>item.id===Number(card.dataset.cardId));if(found)activeElements.dialogContent.innerHTML=cardDialog(found);}if(event.target.closest(".archive-back")&&activeState.selected)activeElements.dialogContent.innerHTML=archetypeDialog(activeState.selected);});
activeElements.dialog.querySelector(".dialog-close").addEventListener("click",()=>activeElements.dialog.close());activeElements.dialog.addEventListener("click",event=>{if(event.target===activeElements.dialog)activeElements.dialog.close();});activeElements.search.addEventListener("input",()=>{activeState.query=activeElements.search.value;renderActive();});
async function loadActive(){try{const response=await fetch(`data/banlist.json?v=${Date.now()}`,{cache:"no-store"});if(!response.ok)throw new Error(`HTTP ${response.status}`);const payload=await response.json();activeState.archetypes=Array.isArray(payload.activeArchetypes)?payload.activeArchetypes:[];activeElements.updated.textContent=payload.updatedAt?`Updated ${new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(payload.updatedAt))}`:"Active field loaded";activeElements.total.textContent=`${activeState.archetypes.length} archetype${activeState.archetypes.length===1?"":"s"}`;renderActive();if(location.hash.startsWith("#archetype-"))openArchetype(Number(location.hash.replace("#archetype-","")));}catch(error){console.error(error);activeElements.error.hidden=false;activeElements.search.hidden=true;activeElements.updated.textContent="Active archetypes unavailable";}}
loadActive();

