const profileState={players:[],active:[],retired:[],matches:[],query:""};
const profileElements={updated:document.querySelector("#profiles-updated"),total:document.querySelector("#profiles-total"),search:document.querySelector("#profiles-search"),grid:document.querySelector("#profiles-grid"),detail:document.querySelector("#profile-detail"),error:document.querySelector("#profiles-error")};
const destinationLabels={ephtear:"Ephtear",duelhalla:"Duelhalla","limb-faux":"Limb-Faux"};
const destinationImages={ephtear:"assets/retirement-ephtear.png",duelhalla:"assets/retirement-duelhalla.png","limb-faux":"assets/retirement-limbfaux.png"};
const escapeHtml=(value="")=>String(value).replace(/[&<>'"]/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[character]);
const dateLabel=value=>{const date=new Date(value);return Number.isNaN(date.valueOf())?"Date unavailable":new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(date);};
const profileUrl=name=>`profiles.html?player=${encodeURIComponent(name)}`;

function renderRoster(){
  const query=profileState.query.trim().toLowerCase();const players=profileState.players.filter(player=>!query||`${player.name} ${player.archetypeName||""}`.toLowerCase().includes(query));
  profileElements.grid.innerHTML=players.length?players.map((player,index)=>`<a class="player-card" href="${profileUrl(player.name)}"><span class="player-card__rank">${index+1}</span><div><strong>${escapeHtml(player.name)}</strong><small>${escapeHtml(player.archetypeName||"No active archetype")}</small></div><span><b>${player.matchWins}-${player.matchLosses}</b><small>matches</small></span><span><b>${player.balance}</b><small>points</small></span></a>`).join(""):'<p class="league-empty">No players match that search.</p>';
}
function resultRow(match,playerName){
  const isReporter=match.reporter===playerName;const ownScore=isReporter?match.reporterGames:match.opponentGames;const otherScore=isReporter?match.opponentGames:match.reporterGames;const opponent=isReporter?match.opponent:match.reporter;const opponentArchetype=isReporter?match.opponentArchetype:match.reporterArchetype;const result=ownScore>otherScore?"Win":ownScore<otherScore?"Loss":"Draw";
  return `<article class="profile-match" data-result="${result.toLowerCase()}"><span>${result}</span><div><strong>vs. ${escapeHtml(opponent)}</strong><small>${escapeHtml(opponentArchetype||"Archetype unavailable")} · ${dateLabel(match.confirmedAt)}</small></div><b>${ownScore}-${otherScore}</b></article>`;
}
function renderProfile(player){
  if(!player){profileElements.detail.hidden=true;return;}
  const rank=profileState.players.findIndex(item=>item.name===player.name)+1;const active=profileState.active.find(entry=>entry.id===player.archetypeId)||profileState.active.find(entry=>entry.creator===player.name);const retired=profileState.retired.filter(entry=>entry.creator===player.name);const matches=profileState.matches.filter(match=>match.reporter===player.name||match.opponent===player.name);
  profileElements.detail.hidden=false;profileElements.detail.innerHTML=`<div class="profile-identity"><div class="profile-monogram">${escapeHtml(player.name.trim().slice(0,2).toUpperCase())}</div><div><a href="profiles.html">← All players</a><p class="eyebrow">League rank #${rank}</p><h2>${escapeHtml(player.name)}</h2><span>${escapeHtml(active?.name||"No active archetype")}</span></div></div><div class="profile-statline"><article><span>Balance</span><strong>${player.balance}</strong><small>${player.lifetimePoints} lifetime points</small></article><article><span>Match record</span><strong>${player.matchWins}-${player.matchLosses}</strong><small>Bot-era confirmed matches</small></article><article><span>Game record</span><strong>${player.gamesWon}-${player.gamesLost}${player.gamesDrawn?`-${player.gamesDrawn}`:""}</strong><small>Includes imported history</small></article><article><span>Retired</span><strong>${retired.length}</strong><small>Recorded archetypes</small></article></div>${active?`<section class="profile-section"><div class="panel-heading"><div><p class="eyebrow">Current campaign</p><h3>Active archetype</h3></div><a href="archetypes.html#archetype-${active.id}">Open full archetype →</a></div><a class="profile-active" href="archetypes.html#archetype-${active.id}">${active.featuredImageUrl?`<img src="${escapeHtml(active.featuredImageUrl)}" alt="" />`:""}<div><span>${active.status==="revived"?"Revived":"Active"}</span><strong>${escapeHtml(active.name)}</strong><small>${active.registeredCardCount} cards · ${active.totalClauses} clauses · ${active.retirementsSeen}/${active.retirementThreshold} retirements seen</small></div></a></section>`:""}<div class="profile-columns"><section class="profile-section"><div class="panel-heading"><div><p class="eyebrow">Permanent history</p><h3>Retired archetypes</h3></div><a href="archive.html">Archive →</a></div><div class="profile-legacies">${retired.length?retired.map(entry=>`<a href="archive.html"><img src="${destinationImages[entry.destination]}" alt="" /><div><strong>${escapeHtml(entry.name)}</strong><small>${destinationLabels[entry.destination]} · ${dateLabel(entry.retiredAt)}</small></div></a>`).join(""):'<p class="league-empty">No retired archetypes recorded.</p>'}</div></section><section class="profile-section"><div class="panel-heading"><div><p class="eyebrow">Duel record</p><h3>Confirmed matches</h3></div><span>${matches.length} recorded</span></div><div class="profile-matches">${matches.length?matches.map(match=>resultRow(match,player.name)).join(""):'<p class="league-empty">No confirmed bot-era matches recorded.</p>'}</div></section></div>`;
  profileElements.detail.scrollIntoView({behavior:"smooth",block:"start"});
}
profileElements.search.addEventListener("input",()=>{profileState.query=profileElements.search.value;renderRoster();});
async function loadProfiles(){try{const response=await fetch(`data/banlist.json?v=${Date.now()}`,{cache:"no-store"});if(!response.ok)throw new Error(`HTTP ${response.status}`);const payload=await response.json();profileState.players=Array.isArray(payload.dashboard?.standings)?payload.dashboard.standings:[];profileState.active=Array.isArray(payload.activeArchetypes)?payload.activeArchetypes:[];profileState.retired=Array.isArray(payload.archetypes)?payload.archetypes:[];profileState.matches=Array.isArray(payload.dashboard?.matchHistory)?payload.dashboard.matchHistory:Array.isArray(payload.dashboard?.recentMatches)?payload.dashboard.recentMatches:[];profileElements.updated.textContent=payload.updatedAt?`Updated ${new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(payload.updatedAt))}`:"Player records loaded";profileElements.total.textContent=`${profileState.players.length} player${profileState.players.length===1?"":"s"}`;renderRoster();const selected=new URLSearchParams(location.search).get("player");if(selected)renderProfile(profileState.players.find(player=>player.name===selected));}catch(error){console.error(error);profileElements.error.hidden=false;profileElements.updated.textContent="Player profiles unavailable";}}
loadProfiles();

